import type { Rng } from "@/core/rng";

import { fromArray } from "@/core/utils";

const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut tempus nulla. In auctor dolor ante. Pellentesque et velit auctor, pellentesque lacus ut, semper elit. Cras lobortis et odio non tincidunt. Curabitur eu turpis ut nisl laoreet bibendum. Cras sodales ligula ut urna egestas rhoncus. Suspendisse rhoncus eleifend cursus. Vivamus ultrices nisl et turpis vulputate viverra. Suspendisse scelerisque commodo dolor non venenatis. Aenean nunc ipsum, imperdiet ac mollis in, lobortis et velit. Donec ac sapien consequat, varius nibh sit amet, scelerisque mauris. Quisque sit amet quam vitae augue tempus sodales. Mauris ac augue ante. Praesent porta maximus tortor, eu blandit nulla vestibulum vitae. Cras facilisis a dui quis elementum.

Nullam in tortor sem. Quisque in nunc a quam ullamcorper congue. Curabitur in consectetur magna. Quisque semper erat non neque gravida vulputate. Nulla blandit ornare nulla, sit amet feugiat ante rhoncus vitae. Sed semper nisl purus, gravida aliquet libero varius eget. Donec ornare risus purus, eu sagittis elit sagittis eu. Morbi finibus laoreet velit, quis euismod nisl volutpat in. Sed consequat ante eu ipsum vestibulum, vel semper ante feugiat. Fusce at ante a diam porttitor sodales. Aliquam erat volutpat. Ut facilisis ligula sit amet felis posuere ultricies. Nunc sit amet pulvinar erat, nec tincidunt ligula.

Phasellus sollicitudin mauris in enim feugiat malesuada. Curabitur egestas quam in enim faucibus, eget luctus lorem scelerisque. Morbi malesuada ultricies dolor vel vehicula. Vivamus sollicitudin tortor orci, vel malesuada mauris commodo sit amet. Mauris justo metus, gravida non ullamcorper sed, pharetra vitae enim. Vestibulum neque urna, finibus a tellus pretium, mollis cursus arcu. Duis sollicitudin erat id arcu euismod placerat. Maecenas fringilla nunc vitae ante sodales interdum. Curabitur id suscipit felis. Curabitur eu libero ipsum.

Donec at magna congue, pharetra dolor vel, dapibus metus. Integer feugiat lectus sit amet placerat rhoncus. Donec congue varius purus, vitae ornare massa. Donec tellus neque, efficitur eu arcu in, blandit aliquet lacus. Aenean vehicula erat eu iaculis commodo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vestibulum urna non justo vulputate, dignissim vulputate dolor viverra. Cras venenatis massa eu fermentum ullamcorper. Sed eget pretium leo, at ornare augue. Curabitur venenatis dictum nisl, ut blandit eros finibus et. In at urna ac eros mollis imperdiet. Etiam lectus purus, molestie placerat bibendum vel, pharetra a mi. Praesent id dignissim lorem. Sed vestibulum tortor a velit euismod, at blandit est scelerisque. Integer facilisis, eros quis eleifend maximus, ex enim imperdiet massa, id interdum leo nisi eu neque.

Duis gravida leo et felis venenatis, ac feugiat magna dignissim. Sed ultricies erat nec sem scelerisque dictum. Cras dolor ipsum, fermentum non sapien id, dictum egestas tortor. Aenean id nibh id nisi iaculis aliquet. Morbi vitae augue condimentum, sagittis erat eget, auctor nibh. Curabitur at ultrices ex. Proin sem nibh, dapibus a viverra eget, scelerisque ac neque. Quisque ex felis, rhoncus vel libero eget, condimentum iaculis nisi. In eu nibh nec felis aliquam fringilla. Donec interdum, mauris in sollicitudin pellentesque, purus arcu dapibus turpis, et malesuada leo odio sed turpis. Vivamus tempor bibendum vestibulum. Suspendisse condimentum neque dolor, ac euismod nunc dignissim in. Nullam et orci vitae elit tristique interdum auctor quis nulla. Duis egestas odio quis eleifend tempus. Duis urna nibh, fermentum quis nibh non, faucibus vehicula libero.

Ut eu volutpat justo. Cras rutrum sagittis condimentum. Aenean eget orci interdum, porttitor lorem a, tristique odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus egestas, mauris ut tincidunt bibendum, ex dolor eleifend mauris, non ultrices elit lectus ornare est. In eu posuere nunc. Pellentesque dapibus volutpat tortor, non elementum purus auctor quis. Fusce pharetra semper dui, ut imperdiet est pellentesque eget. Nulla pharetra, dolor ut dictum pulvinar, lorem dui interdum risus, a venenatis urna orci eu justo. Sed in lectus id erat tincidunt vulputate. Praesent in nisi non nunc condimentum maximus. Quisque ullamcorper aliquam diam, eu volutpat nunc hendrerit eu. Ut scelerisque sodales libero, sit amet cursus justo commodo facilisis. Integer non velit ullamcorper, convallis nulla vel, gravida est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce non pellentesque mauris.

Praesent condimentum, justo at scelerisque imperdiet, magna turpis rhoncus urna, nec laoreet dui arcu eu tortor. Donec sagittis ipsum facilisis dui condimentum, nec porta nisi placerat. Curabitur fermentum est massa, eu suscipit nibh ultrices a. Ut tempor metus vitae porttitor tincidunt. Nulla id nunc nec tellus sollicitudin porttitor non a nisl. Fusce vestibulum bibendum finibus. Donec hendrerit urna felis, at dapibus velit tincidunt in. Sed porta velit eu convallis consectetur. Pellentesque eget erat at nulla auctor sodales. Aliquam erat volutpat.

Suspendisse potenti. Mauris molestie urna vitae arcu gravida, eu convallis mauris elementum. Pellentesque scelerisque ante odio, at feugiat velit tristique eget. Sed consectetur tincidunt orci, eu tempor libero tincidunt ut. Donec viverra lobortis elit eget gravida. Mauris vel arcu massa. Curabitur tempor tristique feugiat. Aliquam sit amet efficitur velit, vel malesuada tortor. Nullam viverra finibus urna vitae luctus. Nam semper sollicitudin augue, ut venenatis sapien elementum sit amet. Sed ornare ullamcorper congue. Fusce luctus et elit in tristique. Vivamus quis tortor vel justo interdum rhoncus id in ligula. Ut molestie tellus a arcu pellentesque, vel volutpat sem lobortis.

Vestibulum facilisis varius commodo. Praesent pretium gravida lectus, consequat scelerisque ipsum ultrices id. Nam vel varius velit. Mauris consequat ornare auctor. Integer scelerisque euismod sem, vitae interdum nisl pretium a. Phasellus faucibus, quam at egestas dapibus, urna est accumsan massa, eu eleifend ante libero a ante. Praesent condimentum metus urna, sed tempor risus luctus et. Integer varius ullamcorper ipsum vel egestas. Sed imperdiet, ipsum ut consectetur dapibus, magna nibh rhoncus nisi, ac tempor arcu risus nec turpis. Donec a tortor imperdiet, tempus metus sed, tincidunt tortor. Integer egestas ut nunc eu condimentum.

Curabitur sed dolor ut orci cursus ultricies. Fusce odio tellus, elementum et pulvinar ornare, lobortis et risus. Sed venenatis non felis in pulvinar. Nam interdum, quam id auctor pulvinar, lacus metus ultrices ipsum, eu commodo ipsum mauris vitae tellus. In tristique ex velit, eu dignissim odio pharetra suscipit. Sed consectetur diam vitae viverra varius. Aliquam varius semper nisl, eget volutpat elit cursus id. Sed ac dolor magna. Quisque sed commodo velit. Pellentesque sit amet blandit dui, non dignissim quam. Quisque non mi erat. Nam consectetur id leo pulvinar pulvinar.`;

export function createLoremDomain(rng: Rng) {
  const paragraph = fromArray(rng, lorem.split(/\n+/));
  const sentence = fromArray(rng, lorem.split(/[\.\!\?]+/).map((s) => s.trim()).filter(Boolean));
  const word = fromArray(rng, lorem.split(/\s+/).map((s) => s.trim()).filter(Boolean));

  return { paragraph, sentence, word };
}
